name: helm

on:
  push:
    branches:
    - '**'
    paths:
      - 'helm/**'

jobs:
  Helm2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: 'Set up Docker Buildx'
      uses: docker/setup-buildx-action@v1

    - name: 'Build Docker image'
      uses: docker/build-push-action@v2
      with:
        context: helm/
        file: helm/Dockerfile
        push: true
        tags: |
          2
          2-debian
        build-args: |
          HELM_VERSION=2

  Helm3:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: 'Set up Docker Buildx'
      uses: docker/setup-buildx-action@v1

    - name: 'Build Docker image'
      uses: docker/build-push-action@v2
      with:
        context: helm/
        file: helm/Dockerfile
        push: true
        tags: |
          3
          3-debian
          debian
          latest
        build-args: |
          HELM_VERSION=3