name: helm

on:
  push:
    branches:
    - '**'
    paths:
      - 'helm/**'

jobs:
  Helm2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: 'Set up Docker Buildx'
      uses: docker/setup-buildx-action@v1

    - name: 'Login to DockerHub'
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: 'Build Docker image'
      uses: docker/build-push-action@v2
      with:
        context: helm/
        file: helm/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/helm:2
          ${{ secrets.DOCKER_HUB_USERNAME }}/helm:2-debian
        build-args: |
          HELM_VERSION=2

  Helm3:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: 'Set up Docker Buildx'
      uses: docker/setup-buildx-action@v1

    - name: 'Login to DockerHub'
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: 'Build Docker image'
      uses: docker/build-push-action@v2
      with:
        context: helm/
        file: helm/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/helm:3
          ${{ secrets.DOCKER_HUB_USERNAME }}/helm:3-debian
          ${{ secrets.DOCKER_HUB_USERNAME }}/helm:debian
          ${{ secrets.DOCKER_HUB_USERNAME }}/helm:latest
        build-args: |
          HELM_VERSION=3